### ISSUE TITLE
Add Contributor profile images below the `README.md` under a new Contributors section.

### ISSUE THREAD

**Issue by karanS08** [karanS08/ctf-tools#126]
Links to contributor's link is in the `CONTRIBUTORS.md` file . If possible make it so that every time someone adds his profile in the `CONTRIBUTORS.md`, it automatically displays it in the `README.md` file.

**Comment by mayurrkukreja** [comment]
Hey! I would like to work on this. Please assign me the issue 👍

**Comment by karanS08** [comment]
@mayurrkukreja  you are good to go . We will merge the PR only if we find the code optimal enough.

**Comment by SahilSingh177** [comment]
Please assign this to me.

**Comment by karanS08** [comment]
@SahilSingh177  you are good to go .
