### ISSUE TITLE
Update the ReadMe

### ISSUE THREAD

**Issue by Aniket1026** [karanS08/ctf-tools#167]
In the Readme you can brief the new comers on how to contribute. Updated changes are like this

<img width="452" alt="ctf reamde update" src="https://user-images.githubusercontent.com/92184189/193851454-41f8bf45-c22d-4935-8118-5bfcc9f244c0.png">

**Comment by Jflyer45** [comment]
I can do this quick

**Comment by Jflyer45** [comment]
Ready for review #177

**Comment by karanS08** [comment]
Heyy @Jflyer45  , Thankyou for contributing . Your PR has been merged . 🎉
