### ISSUE TITLE
Splitting up based on category

### ISSUE THREAD

**Issue by s0LA1337** [karanS08/ctf-tools#23]
I think it would be better that instead of having a category tab, the entries will be split up based on category, so that there is a table for: pwn, re, forensics, ...

**Comment by karanS08** [comment]
Hii  @s0LA1337  , I am not very much familiar with GitHub . I am still in learning stage . I can add you as a contributor and maybe you can help me fix it .After all hacktoberfest is all about learning and helping .

**Comment by s0LA1337** [comment]
Sure i can help you a little.
No need to add me as a member, but it'd be great if you could start merging some prs so that it will make the merging easier.

**Comment by karanS08** [comment]
@s0LA1337  can you please ping me discord i have done something wrong and everything seems to be broken now
